@echo off
cd /d "%~dp0"
if not exist .venv (
    echo Creating virtual environment...
    python -m venv .venv
)
echo Activating virtual environment...
call .venv\Scripts\activate
echo Installing/Verifying dependencies...
pip install -r requirements.txt
echo Launching Streamlit Web App...
streamlit run app.py
pause
